spring:
  application:
    name: user-center-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zjx666
    url: jdbc:mysql://118.89.117.115:3306/guyue
  session:
    timeout: 86400